version: '3.3'
services:
  postgres:
    image: postgres:11
    restart: always
    container_name: spring_data_jpa_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spring_data_jpa_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    command: postgres -N 100